[package]
name = "elegantmath"
version = "0.2.0"
entrypoint = "src/lib.typ"
authors = ["João Barioni"]
license = "MIT"
description = "Elegant template for mathematical documents, exercises and study notes with dark/light themes."
repository = "https://github.com/joaobarioni/elegantmath"
categories = ["math", "academic", "report"]
keywords = ["mathematics", "exercises", "academic", "template", "elegant", "dark-theme"]

[dependencies]
mannot = "0.3.0"
showybox = "2.0.4"

[template]
path = "template"
entrypoint = "main.typ"
